[build]

  command = 'npm run build'
  publish = 'dist'

[[headers]]

  for = '/*'

  [headers.values]

    Strict-Transport-Security = 'max-age=63072000; preload'
    Content-Security-Policy = "default-src 'self'; script-src 'unsafe-inline' 'self' www.googletagmanager.com www.google-analytics.com; connect-src 'self' www.googletagmanager.com www.google-analytics.com; img-src 'self' www.googletagmanager.com www.google-analytics.com; object-src 'none'"
    X-Content-Type-Options = 'nosniff'
    X-Frame-Options = 'DENY'
    X-XSS-Protection = '1; mode=block'
